#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Name, username, friend_list
raw_player_list = [
    [u'Alicia', u'_aliciarguez', [u'Raquel', u'Clara']],
    [u'Ángela', u'Angelaapa', [u'Jinx', u'Raquel']],
    [u'Bombi', u'carlosgg88', [u'Piti']],
    [u'Clara', u'clarabntzz', [u'Ivo', u'Raquel']],
    [u'Claudia', u'Claudia08teran', [u'Kini']],
    [u'Cristian', u'Cris199VA', [u'Jony']],
    [u'Cristina', u'Cristinasutil3', [u'Melissa', u'Jinx']],
    [u'Diana', u'didiixdd', [u'María']],
    [u'Elsa', u'elsitta14', [u'Lucía', u'Jinx']],
    [u'Hugo', u'2Hugo21', [u'Jony']],
    [u'Ivo', u'ivopd_01', [u'Jinx', u'Jony']],
    [u'Jinx', u'jinxsullivan', [u'Ángela', u'Ivo']],
    [u'Jony', u'jony_JRM', [u'Hugo', u'Ivo']],
    [u'Kini', u'danibercy', [u'Claudia', u'Ángela']],
    [u'Laura Natal', u'lauranaatal', [u'Melissa']],
    [u'Laura', u'lauucch', [u'Pablo', u'Rosa']],
    [u'Leticia', u'Leticiagrisuela', [u'Laura Natal', u'Melissa']],
    [u'Lucía', u'lucia_canton', [u'Jinx', u'Elsa']],
    [u'María', u'Mariia0609', [u'Diana']],
    [u'Melissa', u'MelissaShelbyy', [u'Cristina', u'Laura Natal']],
    [u'Miguel', u'MiguiDePan', [u'Jony']],
    [u'Nerey', u'powwerpuffgirl', [u'Eric']],
    [u'Pablo', u'pablincounter', [u'Laura', u'Rosa']],
    [u'Pérez', u'javierperezJP', []],
    [u'Piti', u'petevalencia12', [u'Bombi']],
    [u'Ramón', u'lecunes', [u'Kini']],
    [u'Raquel', u'raquelbntzz', [u'Diana', u'Ángela']],
    [u'Rouus', u'JdBm23n16', []],
    [u'Rik', u'Rik3619', [u'Jony', u'Kini']],
    [u'Rosa', u'larosaliaaa', [u'Laura']],
    [u'Rusín', u'JaviDeLonge182', [u'Jony']],
    [u'Samu', u'samu_cente8', []],
    [u'Victor', u'Victor_Moran22', []],
]
